Repository CodeMentor-CodingSite/JavaServer, pull requests merged in 2023-12, with the labels that each got.

#8 [Test]_파이썬 코드 동작을 위한 테스트 코드
  src/main/java/com/CodeMentor/controller/CodeExecutionController.java
  src/main/java/com/CodeMentor/service/CodeExecutionService.java
Labels: Type: Test

#17 [refactor] JPA Entity, Repo / Java code service update
  .github/workflows/gradle.yml
  .gitignore
  deploy.sh
  src/main/java/com/CodeMentor/code/service/JavaCodeService.java
  src/main/java/com/CodeMentor/question/entity/CodeExecConverter.java
  src/main/java/com/CodeMentor/question/entity/ConverterMap.java
  src/main/java/com/CodeMentor/question/entity/Language.java
  src/main/java/com/CodeMentor/question/entity/Question.java
  src/main/java/com/CodeMentor/question/entity/Question.java~
  src/main/java/com/CodeMentor/question/entity/QuestionTestCase.java
  src/main/java/com/CodeMentor/question/entity/QuestionTestCaseDetail.java
  src/main/java/com/CodeMentor/question/repository/CodeExecConverterRepository.java
  src/main/java/com/CodeMentor/question/repository/ConverterMapRepository.java
  src/main/java/com/CodeMentor/question/repository/QuestionTestCaseRepository.java
  src/main/resources/application.yml
Labels: For: API

#18 #16 문제 관련 관리자 API (또는 테스트용 API)
  src/main/java/com/CodeMentor/question/controller/QuestionController.java
  src/main/java/com/CodeMentor/question/dto/ConverterInputRequest.java
  src/main/java/com/CodeMentor/question/dto/QuestionCodeInputRequest.java
  src/main/java/com/CodeMentor/question/dto/QuestionInputRequest.java
  src/main/java/com/CodeMentor/question/dto/TestCaseDetailDTO.java
  src/main/java/com/CodeMentor/question/dto/TestCaseRequest.java
  src/main/java/com/CodeMentor/question/service/QuestionService.java
Labels: For: API

#19 [Feat] Python코드 실행 API 개발
  src/main/java/com/CodeMentor/code/controller/JavaCodeController.java
  src/main/java/com/CodeMentor/code/controller/PythonCodeController.java
  src/main/java/com/CodeMentor/code/dto/UserCodeRequest.java
  src/main/java/com/CodeMentor/code/service/JavaCodeService.java
  src/main/java/com/CodeMentor/code/service/PythonCodeService.java
  src/main/java/com/CodeMentor/controller/CodeExecutionController.java
Labels: For: API

#21 Question을 입력받을때, ConverterId와 TestCaseDetailId가 추가 메핑되도록 수정
  src/main/java/com/CodeMentor/question/dto/TestCaseDetailDTO.java
  src/main/java/com/CodeMentor/question/service/QuestionService.java
Labels: Type: Refactor

#22 [파이썬] 컨버터 매핑 추가된 파이썬 코드
  src/main/java/com/CodeMentor/code/service/PythonCodeService.java
Labels: For: API

#25 Question Constraint size를 varchar(50)에서 varchar(100)으로 수정
  src/main/java/com/CodeMentor/question/entity/QuestionConstraint.java
Labels: Priority: High, Type: Refactor
